### ISSUE TITLE
Joining Pulumiverse with this provider?

### ISSUE THREAD

**Issue by ringods** [SimCubeLtd/pulumi-onepassword#4]
Hello @prom3theu5, I bumped into your 1Password Pulumi provider today. I was wondering if you are interested in joining [Pulumiverse](https://github.com/pulumiverse), the community around shared maintenance of providers, components, code snippets and other Pulumi related resources.

Joining forces would mean the following:
* this repository is transferred to the Pulumiverse Github organization.
* you remain the core maintainer of this repository
* we can help out with finding additional maintainers
* we can help out with supporting shared build setup
* ...

If you have more questions, you can ask them here and I will follow up in this issue, or you can jump into the #pulumiverse channel on the [Pulumi Community Slack](https://slack.pulumi.com/).

**Comment by prom3theu5** [comment]
Sorry for the late reply on this one
Notifications for this repo were swept up by an inbox rule - I mainly monitor the upstream 1Password terraform provider repo for potential changes

I think this is a good idea
